const $=s=>document.querySelector(s),notice=t=>$('#notice').textContent=t,esc=s=>String(s).replace(/[&<>]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;'}[c]));
const catalog={
  'Data & maps':[['items','DayZ Item Database','Search a bundled local reference catalogue.'],['zombies','Zombie Database','Browse infected reference stats.'],['loot','Interactive Loot Map','Inspect local sample map markers.'],['map','Chernarus 3D Map','Offline terrain/POI preview.'],['editor','DayZ Map Editor','Place objects and export JSON.'],['base','DayZ Base Planner','Build a material list for a planned base.']],
  Editors:[['event','Event Editor','Generate event XML locally.'],['types','Types Updater','Compare two local types.xml files.'],['gameplay','Gameplay Editor','Generate cfgGameplay.json.'],['globals','Globals Editor','Generate globals.xml.'],['mission','Mission Updater','Compare local mission lists.'],['trader','Trader Mod Editor','Build a trader JSON list.']],
  Diagnostics:[['daynight','Day/Night Cycle Calculator','Calculate server acceleration.'],['doctor','CE Doctor','Check pasted types.xml for common CE problems.'],['game','DZGame — Offline Collection','A local saved collection counter.']]
};
const items=[['AKM','Weapon','3.6 kg','Military','3'],['M4A1','Weapon','3.2 kg','Military','4'],['PlateCarrier','Clothing','12 slots','Military','4'],['Apple','Food','0.2 kg','Town','1'],['NailBox','Tool','1 kg','Industrial','2'],['SledgeHammer','Tool','4 kg','Industrial','3']];
const zombies=[['InfectedSoldier','120','Military','High'],['InfectedPolice','100','Police','Medium'],['InfectedFirefighter','110','Town','Medium'],['InfectedCity','90','Town','Low']];
function field(id,label,value='',type='text'){return `<label class="field">${label}<input id="${id}" value="${esc(value)}" type="${type}"></label>`}function button(t='GENERATE'){return `<button class="action" id="go">${t}</button>`}function out(v,name='output.txt'){return `<textarea id="out" readonly>${esc(v)}</textarea><div class="row"><button class="action" id="copy">COPY</button><button class="action alt" id="download">DOWNLOAD</button></div>`}function download(text,name){let a=document.createElement('a');a.href=URL.createObjectURL(new Blob([text],{type:'text/plain'}));a.download=name;a.click();URL.revokeObjectURL(a.href)}
function renderItems(data,title){$('#tool').innerHTML=`<div class="row">${field('q','Search')}</div><div id="rows"></div>`;let draw=()=>{let q=$('#q').value.toLowerCase();let r=data.filter(x=>x.join(' ').toLowerCase().includes(q));$('#rows').innerHTML=`<table class="table"><tr>${title.map(x=>`<th>${x}</th>`).join('')}</tr>${r.map(x=>`<tr>${x.map(y=>`<td>${esc(y)}</td>`).join('')}</tr>`).join('')}</table>`};$('#q').oninput=draw;draw()}
function simpleMap(mode){let pins=mode==='loot'?[['Well',22,63],['Fuel',68,30],['Military loot',45,48],['Heli crash',74,68]]:[['North West Airfield',39,41],['Chernogorsk',63,77],['Elektrozavodsk',73,62],['Green Mountain',48,56]];$('#tool').innerHTML=`<div class="map">${pins.map(p=>`<i class="pin" style="left:${p[1]}%;top:${p[2]}%" title="${p[0]}"></i>`).join('')}</div><p class="result">${mode==='loot'?'Static sample markers. Load the full map pack to expand this catalogue.':'Offline map preview. Terrain and POIs can be bundled as static assets.'}</p>`}
function mapEditor(){let placed=[];const draw=()=>{$('#tool').innerHTML=`<div class="row">${field('obj','Object classname','Land_Wreck_S101')}${field('x','X','7500','number')}${field('y','Y','0','number')}${field('z','Z','9200','number')}${button('PLACE OBJECT')}</div><div class="map" id="canvas">${placed.map(p=>`<i class="pin" style="left:${p.x%100}%;top:${p.z%100}%" title="${p.n}"></i>`).join('')}</div><p class="result">${placed.length} object(s) placed locally.</p><div class="row"><button class="action alt" id="export">EXPORT OBJECT SPAWNER JSON</button></div>`;$('#go').onclick=()=>{placed.push({n:$('#obj').value,x:+$('#x').value,y:+$('#y').value,z:+$('#z').value});draw()};$('#export').onclick=()=>download(JSON.stringify(placed.map(p=>({name:p.n,pos:[p.x,p.y,p.z],ypr:[0,0,0],scale:1})),null,2),'objectspawner.json')};draw()}
function base(){let parts=[];const draw=()=>{$('#tool').innerHTML=`<div class="row">${field('part','Part classname','FenceKit')}${field('qty','Quantity','1','number')}${button('ADD PART')}</div><div class="cards">${parts.map(p=>`<div class="card"><b>${esc(p.n)}</b><small>${p.q} × nails: ${p.q*18} · planks: ${p.q*8}</small></div>`).join('')}</div><p class="result">Total: ${parts.reduce((a,p)=>a+p.q*18,0)} nails · ${parts.reduce((a,p)=>a+p.q*8,0)} planks.</p>`;$('#go').onclick=()=>{parts.push({n:$('#part').value,q:Math.max(1,+$('#qty').value||1)});draw()}};draw()}
function event(){let run=()=>{let [n,no,mi,ma]=['event','nominal','min','max'].map(id=>$('#'+id).value);if(!n||[no,mi,ma].some(x=>!/^\d+$/.test(x)))return notice('Enter an event name and whole-number limits.');$('#tool').innerHTML=out(`<events>\n  <event name="${n}">\n    <nominal>${no}</nominal>\n    <min>${mi}</min>\n    <max>${ma}</max>\n  </event>\n</events>`,'events.xml');bindOutput()};$('#tool').innerHTML=`<div class="row">${field('event','Event name','VehicleOffroadHatchback')}${field('nominal','Nominal','3','number')}${field('min','Minimum','1','number')}${field('max','Maximum','5','number')}${button()}</div>`;$('#go').onclick=run}
function compare(kind){$('#tool').innerHTML=`<p class="result">Paste a current file and a vanilla/reference file. The comparison runs only in this tab.</p><div class="row"><label class="field">CURRENT<textarea id="a"></textarea></label><label class="field">REFERENCE<textarea id="b"></textarea></label></div>${button('COMPARE')}`;$('#go').onclick=()=>{let names=t=>[...t.matchAll(/<type\s+name="([^"]+)"/g)].map(x=>x[1]);let a=names($('#a').value),b=names($('#b').value);if(kind==='mission'){a=$('#a').value.split(/\r?\n/).filter(Boolean);b=$('#b').value.split(/\r?\n/).filter(Boolean)}let missing=b.filter(x=>!a.includes(x));$('#tool').insertAdjacentHTML('beforeend',`<p class="result">${missing.length} missing reference entries: ${missing.slice(0,100).map(esc).join(', ')||'none'}.</p>`)} }
function gameplay(){let run=()=>{let stamina=$('#stamina').value==='on',build=$('#build').value==='on';let json={PlayerData:{disablePersonalLight:false},GeneralData:{enableCrosshair:true},StaminaData:{enableStamina:stamina},BaseBuildingData:{disableBaseDamage:build}};$('#tool').innerHTML=out(JSON.stringify(json,null,2),'cfggameplay.json');bindOutput()};$('#tool').innerHTML=`<div class="row"><label class="field">Stamina<select id="stamina"><option value="on">Enabled</option><option value="off">Disabled</option></select></label><label class="field">Disable base damage<select id="build"><option value="off">No</option><option value="on">Yes</option></select></label>${button()}</div>`;$('#go').onclick=run}
function globals(){let run=()=>{$('#tool').innerHTML=out(`<globals>\n  <var name="CleanupLifetimeDefault" type="0" value="${$('#cleanup').value}" />\n  <var name="FlagRefreshFrequency" type="0" value="${$('#flag').value}" />\n</globals>`,'globals.xml');bindOutput()};$('#tool').innerHTML=`<div class="row">${field('cleanup','Default cleanup seconds','3600','number')}${field('flag','Flag refresh days','45','number')}${button()}</div>`;$('#go').onclick=run}
function daynight(){let run=()=>{let d=+$('#day').value,n=+$('#night').value;if(!(d>0&&n>0))return notice('Use values greater than zero.');$('#tool').innerHTML=out(`serverTimeAcceleration = ${(12/d).toFixed(2)}\nserverNightTimeAcceleration = ${(12/n).toFixed(2)}`,'day-night.txt');bindOutput()};$('#tool').innerHTML=`<div class="row">${field('day','Day hours','3','number')}${field('night','Night hours','1','number')}${button('CALCULATE')}</div>`;$('#go').onclick=run}
function doctor(){ $('#tool').innerHTML=`<p class="result">Paste types.xml to check duplicate item names, invalid number values and min/nominal conflicts.</p><textarea id="xml"></textarea>${button('CHECK XML')}`;$('#go').onclick=()=>{let text=$('#xml').value,doc=new DOMParser().parseFromString(text,'application/xml');if(doc.querySelector('parsererror'))return notice('Invalid XML.');let seen=new Set,issues=[];doc.querySelectorAll('type').forEach(t=>{let n=t.getAttribute('name')||'(unnamed)';if(seen.has(n))issues.push(`Duplicate: ${n}`);seen.add(n);let no=+t.querySelector('nominal')?.textContent,mi=+t.querySelector('min')?.textContent;if(Number.isFinite(no)&&Number.isFinite(mi)&&mi>no)issues.push(`${n}: min is greater than nominal`)});$('#tool').insertAdjacentHTML('beforeend',`<p class="result">${issues.length?issues.map(esc).join('<br>'):'No common CE problems found.'}</p>`)} }
function trader(){let list=[];const draw=()=>{$('#tool').innerHTML=`<div class="row">${field('item','Item classname','AKM')}${field('buy','Buy price','1000','number')}${field('sell','Sell price','700','number')}${button('ADD ITEM')}</div><table class="table"><tr><th>Item</th><th>Buy</th><th>Sell</th></tr>${list.map(x=>`<tr><td>${esc(x.n)}</td><td>${x.b}</td><td>${x.s}</td></tr>`).join('')}</table><div class="row"><button class="action alt" id="export">EXPORT JSON</button></div>`;$('#go').onclick=()=>{list.push({n:$('#item').value,b:+$('#buy').value,s:+$('#sell').value});draw()};$('#export').onclick=()=>download(JSON.stringify({TraderItems:list},null,2),'trader.json')};draw()}
function game(){let count=+localStorage.getItem('sonics-dzgame')||0;$('#tool').innerHTML=`<div class="cards"><div class="card"><b>${count}</b><small>infected cards collected locally</small></div></div><div class="row"><button class="action" id="pack">OPEN PACK</button><button class="action alt" id="reset">RESET COLLECTION</button></div>`;$('#pack').onclick=()=>{localStorage.setItem('sonics-dzgame',++count);game()};$('#reset').onclick=()=>{localStorage.removeItem('sonics-dzgame');game()}}
function bindOutput(){$('#copy').onclick=()=>navigator.clipboard.writeText($('#out').value).then(()=>notice('Copied locally.'));$('#download').onclick=()=>download($('#out').value,'sonics-dayz-output.txt')}
const renderers={items:()=>renderItems(items,['Classname','Kind','Weight / size','Area','Tier']),zombies:()=>renderItems(zombies,['Classname','HP','Area','Threat']),loot:()=>simpleMap('loot'),map:()=>simpleMap('map'),editor:mapEditor,base,event,types:()=>compare('types'),mission:()=>compare('mission'),gameplay,globals,daynight,doctor,trader,game};
function open(id,title,desc,group){$('#group').textContent=group.toUpperCase();$('#title').textContent=title;$('#description').textContent=desc;renderers[id]();document.querySelectorAll('.nav-item').forEach(x=>x.classList.toggle('active',x.dataset.id===id))}let nav='';Object.entries(catalog).forEach(([g,rows])=>{nav+=`<div class="nav-group">${g}</div>`+rows.map(x=>`<button class="nav-item" data-id="${x[0]}">${x[1]}</button>`).join('')});$('#nav').innerHTML=nav;document.querySelectorAll('.nav-item').forEach(b=>b.onclick=()=>{let r=Object.entries(catalog).flatMap(([g,a])=>a.map(x=>[g,...x])).find(x=>x[1]===b.dataset.id);open(r[1],r[2],r[3],r[0])});let first=Object.entries(catalog)[0];open(first[1][0][0],first[1][0][1],first[1][0][2],first[0]);
